services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/db
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend
  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    environment:
      CLICKHOUSE_USER : click
      CLICKHOUSE_PASSWORD : click
    ports: ["8123:8123", "9000:9000"]
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
  airflow:
    image: apache/airflow:2.10.5-python3.12
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/db?options=-csearch_path%3Dairflow
      AIRFLOW__CORE__FERNET_KEY: "change-me-in-production"
      _PIP_ADDITIONAL_REQUIREMENTS: "psycopg2-binary==2.9.10 clickhouse-connect==0.8.18"
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: db
      PG_SCHEMA: bionicpro
      PG_USER: admin
      PG_PASSWORD: admin
      CH_HOST: clickhouse
      CH_PORT: 8123
      CH_DATABASE: prosthesis
      CH_USER: click
      CH_PASSWORD: click
      TELEMETRY_LOOKBACK_MINUTES: 15
    ports:
      - "8090:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: >
      bash -c "
      airflow db migrate && \
      airflow users create -e admin@example.com -f Airflow -l Airflow -u admin -p admin -r Admin; 
      airflow webserver --port 8080 & airflow scheduler
      "
  prosthesis-service:
    build:
      context: ./prosthesis-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PG_DB_URL: jdbc:postgresql://postgres:5432/db
      PG_DB_SCHEMA: bionicpro
      PG_DB_USERNAME: admin
      PG_DB_PASSWORD: admin
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/reports-realm/protocol/openid-connect/certs
      CL_DB_URL: jdbc:clickhouse://clickhouse:8123/prosthesis
      CL_DB_USERNAME: click
      CL_DB_PASSWORD: click
volumes:
  postgres-data:
  clickhouse-data:
  airflow_data: